using Blazor.Infrastructure.Entities;
using Dominus.Backend.Application;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Npgsql;
using Oracle.ManagedDataAccess.Client;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Dominus.Backend.DataBase
{
    public class DContext : DbContext
    {
        public DbSet<AuditFW> AuditFW { get; set; }

        protected DataBaseSetting setting;

        public DataBaseSetting Setting
        {
            get { return setting; }
        }

        public DContext(DataBaseSetting setting)
        {
            this.setting = setting;
        }

        public override int SaveChanges()
        {
            var auditEntries = OnBeforeSaveChanges();
            var result = base.SaveChanges();
            OnAfterSaveChanges(auditEntries);
            return result;
        }

        private int OnAfterSaveChanges(List<AuditFWEntry> auditEntries)
        {
            if (auditEntries == null || auditEntries.Count == 0)
                return 0;

            foreach (var auditEntry in auditEntries)
            {
                // Get the final value of the temporary properties
                foreach (var prop in auditEntry.TemporaryProperties)
                {
                    if (prop.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                    else
                    {
                        auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                }

                // Save the Audit entry
                AuditFW.Add(auditEntry.ToAuditFW());
            }

            return SaveChanges();
        }

        private List<AuditFWEntry> OnBeforeSaveChanges()
        {
            PropertyValues oldDbValues = null;
            ChangeTracker.DetectChanges();
            var auditEntries = new List<AuditFWEntry>();
            foreach (var entry in ChangeTracker.Entries())
            {
                if (entry.Entity is AuditFW || entry.State == EntityState.Detached || entry.State == EntityState.Unchanged)
                    continue;
                if (entry.State == EntityState.Modified)
                    oldDbValues = entry.GetDatabaseValues();
                var auditEntry = new AuditFWEntry(entry);

                auditEntry.TableName = entry.Metadata.GetTableName();
                auditEntry.TransactionDate = DateTime.Now;
                auditEntry.CreationDate = DateTime.Now;
                auditEntry.LastUpdate = DateTime.Now;
                auditEntry.CreatedBy = "admin";
                auditEntry.UpdatedBy = "admin";

                auditEntries.Add(auditEntry);

                foreach (var property in entry.Properties)
                {

                    if (property.IsTemporary)
                    {
                        // value will be generated by the database, get the value after saving
                        auditEntry.TemporaryProperties.Add(property);
                        continue;
                    }

                    string propertyName = property.Metadata.Name;

                    if (propertyName == "UpdatedBy")
                    {
                        auditEntry.CreatedBy = property.CurrentValue.ToString();
                        auditEntry.UpdatedBy = property.CurrentValue.ToString();
                    }

                    if (property.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[propertyName] = property.CurrentValue;
                        continue;
                    }

                    switch (entry.State)
                    {
                        case EntityState.Added:
                            auditEntry.Action = Enum.GetName(typeof(EntityState), EntityState.Added);
                            auditEntry.NewValues[propertyName] = property.CurrentValue;
                            break;

                        case EntityState.Deleted:
                            auditEntry.Action = Enum.GetName(typeof(EntityState), EntityState.Deleted);
                            auditEntry.OldValues[propertyName] = property.OriginalValue;
                            break;

                        case EntityState.Modified:
                            if (property.IsModified && (property.CurrentValue == null ? "" : property.CurrentValue.ToString()) != (oldDbValues.GetValue<object>(property.Metadata.Name) == null ? "" : oldDbValues.GetValue<object>(property.Metadata.Name).ToString()))
                            {
                                auditEntry.Action = Enum.GetName(typeof(EntityState), EntityState.Modified);
                                auditEntry.OldValues[propertyName] = oldDbValues.GetValue<object>(property.Metadata.Name);
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                            }
                            break;
                    }
                }


            }

            // Save audit entities that have all the modifications
            foreach (var auditEntry in auditEntries.Where(_ => !_.HasTemporaryProperties))
            {
                AuditFW.Add(auditEntry.ToAuditFW());
            }

            // keep a list of entries where the value of some properties are unknown at this step
            return auditEntries.Where(_ => _.HasTemporaryProperties).ToList();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            if (setting.DataBaseType == DataBaseType.SQLServer)
            {
                optionsBuilder.UseSqlServer(GetConnectionString(setting))
                    //.ConfigureWarnings(warnings => warnings.Ignore(CoreEventId.IncludeIgnoredWarning))
                    //.ConfigureWarnings(warnings => warnings.Ignore(CoreEventId.NavigationIncluded))
                    //.ConfigureWarnings(x => x.Throw(RelationalEventId.QueryClientEvaluationWarning))
                    .EnableSensitiveDataLogging(DApp.IsHostDevelopment)
                    .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
            }
            else if (setting.DataBaseType == DataBaseType.Oracle)
            {

            }
            //else if (setting.DataBaseType == DataBaseType.MySql)
                //optionsBuilder.UseMySQL(GetConnectionString(setting));
            else if (setting.DataBaseType == DataBaseType.PostgreSQL)
                optionsBuilder.UseNpgsql(GetConnectionString(setting));
        }

        private string GetConnectionString(DataBaseSetting settings)
        {
            string connectionString = "";
            int timeout = 300;
            if (settings.DataBaseType == DataBaseType.SQLServer)
            {
                SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder();
                builder.DataSource = settings.DataSource;
                builder.InitialCatalog = settings.InitialCatalog;
                builder.IntegratedSecurity = false;
                builder.MultipleActiveResultSets = true;
                builder.UserID = settings.UserId;
                builder.Password = settings.Password;
                builder.UserInstance = false;
                builder.ConnectTimeout = timeout;
                connectionString = builder.ConnectionString;
            }
            if (settings.DataBaseType == DataBaseType.Oracle)
            {
                OracleConnectionStringBuilder builder = new OracleConnectionStringBuilder();
                builder.DataSource = settings.DataSource;
                //builder. = settings.InitialCatalog;
                //builder.IntegratedSecurity = false;
                //builder.MultipleActiveResultSets = true;
                builder.UserID = settings.UserId;
                builder.Password = settings.Password;
                //builder.UserInstance = false;
                builder.ConnectionTimeout = timeout;
                connectionString = builder.ConnectionString;
            }
            //else if (settings.DataBaseType == DataBaseType.MySql)
            //{
            //    MySqlConnectionStringBuilder builder = new MySqlConnectionStringBuilder();
            //    builder.Server = settings.DataSource;
            //    builder.Database = settings.InitialCatalog;
            //    builder.UserID = settings.UserId;
            //    builder.Password = settings.Password;
            //    builder.ConnectionTimeout = Convert.ToUInt32(timeout);
            //    builder.ConvertZeroDateTime = true;
            //    connectionString = builder.ConnectionString;
            //}
            else if (settings.DataBaseType == DataBaseType.PostgreSQL)
            {
                NpgsqlConnectionStringBuilder builder = new NpgsqlConnectionStringBuilder();
                builder.Host = settings.DataSource;
                builder.Database = settings.InitialCatalog;
                builder.Username = settings.UserId;
                builder.Password = settings.Password;
                builder.Timeout = timeout;
                connectionString = builder.ConnectionString;
            }
            return connectionString;
        }
    }
}