using System.Collections.Generic;
using System.ComponentModel;

namespace Blazor.BusinessLogic.Models
{
    public class ArchivoDescargaModel
    {
        public string Nombre { get; set; }
        public string ContentType { get; set; }
        public string Extension { get; set; }
        public string FullPath { get; set; }
        public byte[] Archivo { get; set; }

        public static string ObtenerContentTypePorExtension(string extension)
        {
            extension = extension.ToLower();
            if (extension.StartsWith("."))
                extension = extension.Replace(".", "");

            string contentType = "application/octet-stream";

            if (ArchivoDescargaModel.ArchivoContentTypes.ContainsKey(extension))
                contentType = ArchivoDescargaModel.ArchivoContentTypes[extension];
            return contentType;
        }

        public static Dictionary<string, string> ArchivoContentTypes = new Dictionary<string, string>
        {
            {"3gp", "video/3gpp"},
            {"7z", "application/x-7z-compressed"},
            {"accdb", "application/msaccess"},
            {"ai", "application/illustrator"},
            {"apk", "application/vnd.android.package-archive"},
            {"arw", "image/x-dcraw"},
            {"avi", "video/x-msvideo"},
            {"bash", "text/x-shellscript"},
            {"bat", "application/x-msdos-program"},
            {"blend", "application/x-blender"},
            {"bin", "application/x-bin"},
            {"bmp", "image/bmp"},
            {"bpg", "image/bpg"},
            {"bz2", "application/x-bzip2"},
            {"cb7", "application/x-cbr"},
            {"cba", "application/x-cbr"},
            {"cbr", "application/x-cbr"},
            {"cbt", "application/x-cbr"},
            {"cbtc", "application/x-cbr"},
            {"cbz", "application/x-cbr"},
            {"cc", "text/x-c"},
            {"cdr", "application/coreldraw"},
            {"class", "application/java"},
            {"cnf", "text/plain"},
            {"conf", "text/plain"},
            {"cpp", "text/x-c++src"},
            {"cr2", "image/x-dcraw"},
            {"css", "text/css"},
            {"csv", "text/csv"},
            {"cvbdl", "application/x-cbr"},
            {"c", "text/x-c"},
            {"c++", "text/x-c++src"},
            {"dcr", "image/x-dcraw"},
            {"deb", "application/x-deb"},
            {"dng", "image/x-dcraw"},
            {"doc", "application/msword"},
            {"docm", "application/vnd.ms-word.document.macroEnabled.12"},
            {"docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
            {"dot", "application/msword"},
            {"dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template"},
            {"dv", "video/dv"},
            {"eot", "application/vnd.ms-fontobject"},
            {"epub", "application/epub+zip"},
            {"eps", "application/postscript"},
            {"erf", "image/x-dcraw"},
            {"exe", "application/x-ms-dos-executable"},
            {"flac", "audio/flac"},
            {"flv", "video/x-flv"},
            {"gif", "image/gif"},
            {"gpx", "application/gpx+xml"},
            {"gz", "application/gzip"},
            {"gzip", "application/gzip"},
            {"h", "text/x-h"},
            {"heic", "image/heic"},
            {"heif", "image/heif"},
            {"hh", "text/x-h"},
            {"hpp", "text/x-h"},
            {"htaccess", "text/plain"},
            {"ical", "text/calendar"},
            {"ics", "text/calendar"},
            {"iiq", "image/x-dcraw"},
            {"impress", "text/impress"},
            {"java", "text/x-java-source"},
            {"jp2", "image/jp2"},
            {"jpeg", "image/jpeg"},
            {"jpg", "image/jpeg"},
            {"jps", "image/jpeg"},
            {"k25", "image/x-dcraw"},
            {"kdc", "image/x-dcraw"},
            {"key", "application/x-iwork-keynote-sffkey"},
            {"keynote", "application/x-iwork-keynote-sffkey"},
            {"kml", "application/vnd.google-earth.kml+xml"},
            {"kmz", "application/vnd.google-earth.kmz"},
            {"kra", "application/x-krita"},
            {"ldif", "text/x-ldif"},
            {"love", "application/x-love-game"},
            {"lwp", "application/vnd.lotus-wordpro"},
            {"m2t", "video/mp2t"},
            {"m3u", "audio/mpegurl"},
            {"m3u8", "audio/mpegurl"},
            {"m4a", "audio/mp4"},
            {"m4b", "audio/m4b"},
            {"m4v", "video/mp4"},
            {"mdb", "application/msaccess"},
            {"mef", "image/x-dcraw"},
            {"mkv", "video/x-matroska"},
            {"mobi", "application/x-mobipocket-ebook"},
            {"mov", "video/quicktime"},
            {"mp3", "audio/mpeg"},
            {"mp4", "video/mp4"},
            {"mpeg", "video/mpeg"},
            {"mpg", "video/mpeg"},
            {"mpo", "image/jpeg"},
            {"msi", "application/x-msi"},
            {"mts", "video/MP2T"},
            {"mt2s", "video/MP2T"},
            {"nef", "image/x-dcraw"},
            {"numbers", "application/x-iwork-numbers-sffnumbers"},
            {"odf", "application/vnd.oasis.opendocument.formula"},
            {"odg", "application/vnd.oasis.opendocument.graphics"},
            {"odp", "application/vnd.oasis.opendocument.presentation"},
            {"ods", "application/vnd.oasis.opendocument.spreadsheet"},
            {"odt", "application/vnd.oasis.opendocument.text"},
            {"oga", "audio/ogg"},
            {"ogg", "audio/ogg"},
            {"ogv", "video/ogg"},
            {"one", "application/msonenote"},
            {"opus", "audio/ogg"},
            {"orf", "image/x-dcraw"},
            {"otf", "application/font-sfnt"},
            {"pages", "application/x-iwork-pages-sffpages"},
            {"pdf", "application/pdf"},
            {"pfb", "application/x-font"},
            {"pef", "image/x-dcraw"},
            {"php", "application/x-php"},
            {"pl", "application/x-perl"},
            {"pls", "audio/x-scpls"},
            {"png", "image/png"},
            {"pot", "application/vnd.ms-powerpoint"},
            {"potm", "application/vnd.ms-powerpoint.template.macroEnabled.12"},
            {"potx", "application/vnd.openxmlformats-officedocument.presentationml.template"},
            {"ppa", "application/vnd.ms-powerpoint"},
            {"ppam", "application/vnd.ms-powerpoint.addin.macroEnabled.12"},
            {"pps", "application/vnd.ms-powerpoint"},
            {"ppsm", "application/vnd.ms-powerpoint.slideshow.macroEnabled.12"},
            {"ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow"},
            {"ppt", "application/vnd.ms-powerpoint"},
            {"pptm", "application/vnd.ms-powerpoint.presentation.macroEnabled.12"},
            {"pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
            {"ps", "application/postscript"},
            {"psd", "application/x-photoshop"},
            {"py", "text/x-python"},
            {"raf", "image/x-dcraw"},
            {"rar", "application/x-rar-compressed"},
            {"reveal", "text/reveal"},
            {"rss", "application/rss+xml"},
            {"rtf", "application/rtf"},
            {"rw2", "image/x-dcraw"},
            {"schema", "text/plain"},
            {"sgf", "application/sgf"},
            {"sh-lib", "text/x-shellscript"},
            {"sh", "text/x-shellscript"},
            {"srf", "image/x-dcraw"},
            {"sr2", "image/x-dcraw"},
            {"tar", "application/x-tar"},
            {"tar.bz2", "application/x-bzip2"},
            {"tar.gz", "application/x-compressed"},
            {"tbz2", "application/x-bzip2"},
            {"tcx", "application/vnd.garmin.tcx+xml"},
            {"tex", "application/x-tex"},
            {"tgz", "application/x-compressed"},
            {"tiff", "image/tiff"},
            {"tif", "image/tiff"},
            {"ttf", "application/font-sfnt"},
            {"txt", "text/plain"},
            {"vcard", "text/vcard"},
            {"vcf", "text/vcard"},
            {"vob", "video/dvd"},
            {"vsd", "application/vnd.visio"},
            {"vsdm", "application/vnd.ms-visio.drawing.macroEnabled.12"},
            {"vsdx", "application/vnd.ms-visio.drawing"},
            {"vssm", "application/vnd.ms-visio.stencil.macroEnabled.12"},
            {"vssx", "application/vnd.ms-visio.stencil"},
            {"vstm", "application/vnd.ms-visio.template.macroEnabled.12"},
            {"vstx", "application/vnd.ms-visio.template"},
            {"wav", "audio/wav"},
            {"webm", "video/webm"},
            {"woff", "application/font-woff"},
            {"wpd", "application/vnd.wordperfect"},
            {"wmv", "video/x-ms-wmv"},
            {"xcf", "application/x-gimp"},
            {"xla", "application/vnd.ms-excel"},
            {"xlam", "application/vnd.ms-excel.addin.macroEnabled.12"},
            {"xls", "application/vnd.ms-excel"},
            {"xlsb", "application/vnd.ms-excel.sheet.binary.macroEnabled.12"},
            {"xlsm", "application/vnd.ms-excel.sheet.macroEnabled.12"},
            {"xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
            {"xlt", "application/vnd.ms-excel"},
            {"xltm", "application/vnd.ms-excel.template.macroEnabled.12"},
            {"xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
            {"xrf", "image/x-dcraw"},
            {"yaml", "application/yaml"},
            {"yml", "application/yaml"},
            {"zip", "application/zip"},
            {"url", "application/internet-shortcut"},
            {"webloc", "application/internet-shortcut"},
            {"js", "application/javascript"},
            {"json", "application/json"},
            {"fb2", "application/x-fictionbook+xml"},
            {"html", "text/html"},
            {"htm", "text/html"},
            {"svg", "image/svg+xml"},
            {"swf", "application/x-shockwave-flash"},
            {"xml", "application/xml"}
        };
    }
}
